# Generated by Django 2.2.6 on 2019-10-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20191030_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postview',
            name='name',
        ),
    ]
