# Generated by Django 2.2.6 on 2019-11-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_remove_postview_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
